### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by omegaga** [flyer103/zhihu#3]
There's a bug in `login` method in `class ZhiHuQuestions`. The method attempts to get `xsrf_token` in login page, while it is executed even before the session sends the first request. So in fact it gets nothing.

Zhihu seems to update its login policy, in my case CAPTCHA is frequently required to login.

**Comment by flyer103** [comment]
Thank you for your feedback.  At the weekend I will solve this problem.

**Comment by omegaga** [comment]
I have written some code on it. I read the CAPTCHA using PIL. Note that the CAPTCHA image should be retrieved with cookies, or it would be invalid.
